### ISSUE TITLE
Interested on contributing deepbots-panda into deepworlds? 

### ISSUE THREAD

**Issue by eakirtas** [KelvinYang0320/deepbots-panda#1]
Hello @KelvinYang0320,

First of all, congratulation for this works, it is amazing! 

I would like to ask you if you are interested on contributing deepbots-panda at [deepworlds repository](https://github.com/aidudezzz/deepworlds)? Deepworlds repository aims to collect various robotics scenarios that can be used as testbeds for students and researchers. Collecting multiple scenarios in one place might be useful for DRL open-source community. You can contribute deepbots-panda by opening a PR in deepworlds and we provide you an extensive code review. Feel free to ask for help. 

Thank you in advance

**Comment by KelvinYang0320** [comment]
@ManosMagnus Thank you for your deepbots and your compliments. Your deepbots really benefits our Panda project. I am interested in contributing it at deepworlds repo. After doing deepbots-panda code refactoring, i will open a PR.

**Comment by KelvinYang0320** [comment]
@ManosMagnus 
It might take more time for me to deal with some bugs and refactoring before contributing deepbots-panda into deepworld since I found some issues when doing deepbots-panda code refactoring.
