### ISSUE TITLE
Question: action space

### ISSUE THREAD

**Issue by YiEdge** [KelvinYang0320/deepbots-panda#5]
Hello, Could you please tell me why the action space size is 2187, if the robot has 7 motors?

**Comment by KelvinYang0320** [comment]
I used PPO with discrete action space, so a 7 degree of freedom system with the coarsest discretization a_i ∈ {−k, 0, k} for each joint leads to an action space with dimensionality: 3^7 = 2187.

However, I think it is better to do this experiment with continuous action space. :sweat_smile:.
